import { StyleSheet, Platform } from "react-native";
import { colores } from "./colores";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colores.azulProfundo,
  },
  content: {
    paddingHorizontal: 15,
    paddingTop: 16,
    paddingBottom: 110,
    flexGrow: 1,
  },
  header: {
    paddingHorizontal: 25,
    paddingTop: 10,
    paddingBottom: 10,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
  },
  headerText: {
    flex: 1,
  },
  refreshButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: colores.azulProfundoClaro,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.16)",
  },
  refreshButtonDisabled: {
    opacity: 0.55,
  },
  infoGrid: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  infoBlock: {
    flex: 1,
    minHeight: 82,
    backgroundColor: colores.azulProfundoClaro,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  infoLabel: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  infoValue: {
    color: colores.blanco,
    fontSize: 16,
    fontWeight: "800",
    marginTop: 6,
  },
  infoSubvalue: {
    color: colores.secundario,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },
  infoError: {
    color: colores.alert,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 4,
  },
  eyebrow: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  title: {
    color: colores.blanco,
    fontSize: 30,
    fontWeight: "900",
    marginTop: 2,
  },
  subtitle: {
    color: colores.secundario,
    fontSize: 15,
    marginTop: 6,
  },
  card: {
    marginBottom: 16,
    backgroundColor: colores.azulProfundoClaro,
    borderRadius: 8,
    padding: 18,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
      },
      android: {
        elevation: 6,
      },
    }),
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  routineName: {
    color: colores.blanco,
    fontSize: 21,
    fontWeight: "800",
    flex: 1,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
    gap: 8,
  },
  pill: {
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  pillText: {
    color: colores.cian,
    fontSize: 13,
    fontWeight: "700",
  },
  addButton: {
    minHeight: 44,
    marginTop: 16,
    borderRadius: 6,
    backgroundColor: colores.verdeOpaco,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailAddButton: {
    marginTop: 18,
    marginBottom: 4,
  },
  addButtonDisabled: {
    backgroundColor: "rgba(29, 191, 132, 0.45)",
  },
  addButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  emptyBox: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  emptyText: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
  },
  loading: {
    marginTop: 50,
  },
  errorBox: {
    backgroundColor: "rgba(213, 134, 145, 0.14)",
    borderColor: colores.alert,
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    marginHorizontal: 15,
    marginTop: 10,
  },
  errorText: {
    color: colores.alert,
    fontSize: 14,
    textAlign: "center",
    fontWeight: "700",
  },
  retryButton: {
    alignSelf: "center",
    backgroundColor: colores.verdeOpaco,
    borderRadius: 6,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginTop: 14,
  },
  retryText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
  },
  detailContainer: {
    flex: 1,
    backgroundColor: colores.azulProfundo,
    paddingTop: 26,
  },
  detailContent: {
    paddingHorizontal: 18,
    paddingBottom: 40,
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  detailTitle: {
    color: colores.blanco,
    fontSize: 26,
    fontWeight: "900",
    textAlign: "center",
    flex: 1,
    marginRight: 35,
  },
  sectionTitle: {
    color: colores.blanco,
    fontSize: 18,
    fontWeight: "800",
    marginTop: 10,
    marginBottom: 14,
  },
  exerciseCard: {
    backgroundColor: colores.azulProfundoClaro,
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  exerciseName: {
    color: colores.blanco,
    fontSize: 18,
    fontWeight: "800",
  },
  exerciseGroup: {
    color: colores.cian,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 4,
  },
  exerciseInfo: {
    color: colores.secundario,
    fontSize: 15,
    fontWeight: "600",
    marginTop: 10,
  },
  comments: {
    color: colores.blanco,
    fontSize: 14,
    marginTop: 8,
    lineHeight: 20,
  },
});
